export const style = {
  editionContainer: {
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    minWidth: '1200px',
    maxWidth: '1200px',
    width: '100%',
    height: '100%',
    color: 'white',
  },
  editionTopContents: {
    minWidth: '1200px',
    maxWidth: '1200px',
    width: '100%',
    height: '1000px',

    display: 'flex',
    flexDirection: 'row',
  },
  editionTopLeftContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: '5',
    width: '100%',
    height: '100%',
  },
  editionTopRightContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: '7',
    width: '100%',
    height: '100%',
    backgroundColor: 'gray',
  },
  editionImgContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: 'yellow',
  },
  editionMusicContainer: { backgroundColor: 'gray' },
  editionTitleContainer: { backgroundColor: 'white' },
  editionOwnerContainer: { backgroundColor: 'brown' },
  editionPriceContainer: { backgroundColor: 'orange' },
  eiditionDetailsContainer: { backgroundColor: 'purple' },
};
