export const style = {
  imgwrapper: {
    position: 'relative',
    height: '250px',
    width: '250px',
    border: 'none',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  wrapper: {
    position: 'relative',
    height: '250px',
    width: '250px',
    border: '2px dashed #c2cdda',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  image: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    fontSize: '20px',
    fontWeight: '500',
    color: '#5b5b7b',
  },
  cancelBtn: [
    {
      position: 'absolute',
      fontSize: '20px',
      right: '15px',
      top: '15px',
      color: '#9658fe',
      cursor: 'pointer',
      fontWeight: '600',
      // display: 'none',
    },
    {
      '&:hover': {
        color: 'red',
      },
    },
  ],
  fileName: {
    position: 'absolute',
    bottom: '0px',
    width: '100%',
    padding: '8px 0',
    fontSize: '18px',
    color: 'black',
    // display: 'none',
  },
  uploadBtn: {
    marginTop: '30px',
    display: 'block',
    width: '100%',
    height: '50px',
    border: 'none',
    outline: 'none',
    borderRadius: '25px',
    color: '#fff',
    fontSize: '18px',
    fontWeight: '500',
    letterSpacing: '1px',
    textTransform: 'uppercase',
    cursor: 'pointer',
    // background: 'linear-gradient(135deg, #3a8ffe 0%, #9658fe 100%)',
  },
};
