export const style = {
  marketplaceAllContainer: { margin: '0 80px' },
  marketplaceHeader: {
    width: '100%',
    minWidth: '1600px',
    maxWidth: '1600px',
    color: 'white',
    lineHeight: '72px',
    paddingTop: '100px',
    paddingBottom: '100px',
    fontSize: '30px',
    fontWeight: '700',
  },
  marketplaceContainer: {
    width: '100%',
    minWidth: '1600px',
    maxWidth: '1600px',
    height: '100%',
    display: 'flex',
    color: 'white',
    margin: '0 40px',
  },
  marketplaceLeftSideBar: { flex: 3 },
  marketplaceWrapper: { flex: 11, paddingRight: '100px' },
};
