export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';
export const USER_IMAGES_REQUEST = 'USER_IMAGES_REQUEST';
export const USER_IMAGES_SUCCESS = 'USER_IMAGES_SUCCESS';
export const USER_IMAGES_FAILURE = 'USER_IMAGES_FAILURE';
export const MY_INFO_REQUEST = 'MY_INFO_REQUEST';
export const MY_INFO_SUCCESS = 'MY_INFO_SUCCESS';
export const MY_INFO_FAILURE = 'MY_INFO_FAILURE';

export const METAMASK_REQUEST = 'METAMASK_REQUEST';
export const METAMASK_SUCCESS = 'METAMASK_SUCCESS';
export const METAMASK_FAILURE = 'METAMASK_FAILURE';
export const METAMASK_LOGIN_REQUEST = 'METAMASK_LOGIN_REQUEST';
export const METAMASK_LOGIN_SUCCESS = 'METAMASK_LOGIN_SUCCESS';
export const METAMASK_LOGIN_FAILURE = 'METAMASK_LOGIN_FAILURE';

export const S3_ALBUMCOVER_REQUEST = 'S3_ALBUMCOVER_REQUEST';
export const S3_ALBUMCOVER_SUCCESS = 'S3_ALBUMCOVER_SUCCESS';
export const S3_ALBUMCOVER_FAILURE = 'S3_ALBUMCOVER_FAILURE';

export const IPFS_MUSIC_REQUEST = 'IPFS_MUSIC_REQUEST';
export const IPFS_MUSIC_SUCCESS = 'IPFS_MUSIC_SUCCESS';
export const IPFS_MUSIC_FAILURE = 'IPFS_MUSIC_FAILURE';

export const MINT_MUSIC_NFT_REQUEST = 'MINT_MUSIC_NFT_REQUEST';
export const MINT_MUSIC_NFT_SUCCESS = 'MINT_MUSIC_NFT_SUCCESS';
export const MINT_MUSIC_NFT_FAILURE = 'MINT_MUSIC_NFT_FAILURE';
